### ISSUE TITLE
Unable to load /docs and /redoc

### ISSUE THREAD

**Issue by samedii** [busykoala/fastapi-opa#35]
**Describe the bug**
I tried to follow your example for OIDC + OPA and I'm unable to see the documentation. I suspect it is because `fastapi-opa` is causing a redirect instead of returning the openapi.json (see the log below). Maybe it is redirecting to login?

**To Reproduce**
Follow this guide https://github.com/busykoala/fastapi-opa/wiki#dev-setup and try to access /docs or /redoc

**Expected behavior**
Expected to be able to use /docs interactively and login like in the fastapi examples like here https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/
![image](https://user-images.githubusercontent.com/1872050/132914324-aa188fc1-71f9-4b23-833a-432d989e03f4.png)

**Screenshots**
```
test-fastapi-keycloak_1  | INFO:     127.0.0.1:42760 - "GET /redoc?session_state=bb916ff5-4570-41c1-8bea-1a28b1ba767e&code=d2170d1c-feae-4150-8274-7273924d5347.bb916ff5-4570-41c1-8bea-1a28b1ba767e.f70a6f2b-5f7f-4ce0-8c47-e80b58c40fbc HTTP/1.1" 200 OK
test-fastapi-keycloak_1  | INFO:     127.0.0.1:42760 - "GET /openapi.json HTTP/1.1" 307 Temporary Redirect
```

**Additional context**
Possibly related, I'm not sure that we need to save anything as a query parameter. Here is an alternative implementation that I've used before for auth0 https://github.com/dorinclisu/fastapi-auth0 that does not modify the url. Maybe this is a limitation enforced by OPA though?

**Comment by busykoala** [comment]
Thanks for reporting the bug. I'll try to address the issue asap, but it might take a while till I get the time. Feel free to open a PR to accelerate the process.

**Comment by busykoala** [comment]
Hi @samedii, I've whitelisted the endpoints `/docs`, `/redoc` and `/openapi.json` in #38 since they really should not be protected by the middleware.

One limitation which will still remain is that the openapi documentation does not show the protection (authentication/authorization) on all the endpoints. This is due to the fact that the authorization policies are not part of the middleware (OPA policies). Also the authentication is very hard to show there since the middleware allows various injectables (incl. custom ones) for the authentication.
