### ISSUE TITLE
OpenId Connect example from documentation doesn't redirect to login anymore.

### ISSUE THREAD

**Issue by ejsyx** [busykoala/fastapi-opa#53]
First off, I'm excited about this library. After spending more time than I want to admit looking for a good ASGI middleware that does oidc token validation out of the box.

It's a minor issue as propably no one would want to run that way without a frontend client***. I could write a pull request if you want, but I wonder about future plans/needs of this project.It would be nicer to split out authn functions as their own standalone middleware.

**Describe the bug**
bug was introduced here https://github.com/busykoala/fastapi-opa/commit/701e5a673cd84b41c83eed345ce08a7a048af496#r79824655 the if not successfull comes before the redirect

**To Reproduce**
Follow documentation at https://github.com/busykoala/fastapi-opa/wiki#dev-setup

*** if using fastapi-opa without some sort of SPA or client is intended, https://github.com/simonw/asgi-auth-github has a nice implementation of usign a cookie (reduces load on the identity provider) and also splits the authorization function from the callback_url, your design does both at the same time.

**Comment by busykoala** [comment]
Hi @ejsyx 
Thank you so much for opening the issue. This indeed is an problem I didn't see in the code review.
If you were able to open a PR the issue can be resolved faster, but I will do it asap otherwise.

I planned to refactor the code to better separate authn and authz and would also be open to discuss a separation.
The challenge I see with separation is keeping the interface stable, for passing the user info gathered in authn to the authz middleware, since the user info is an essential part for authz usually.
