### ISSUE TITLE
importlib-metadata >= 5.0

### ISSUE THREAD

**Issue by maarek** [busykoala/fastapi-opa#63]
Can importlib-metadata be bumped to >= 5.0? I am also not seeing its use in this library but maybe it can be removed?

**Comment by busykoala** [comment]
Thank you for pointing that out. I didn't realize it was still there, but I've removed it in the latest version (v1.4.5).

The reason it was there originally was to use flake9 for linting, so we wouldn't need an extra config file. However, since flake8 has advanced further than flake9, I've decided to switch to flake8 instead, even though it can't be configured in pyproject.toml.

The benefit of not pinning down the software version seems much greater than the inconvenience of adding another config file.
